description: "🎮 Pong Evolved: Battle AI, compete in tournaments, or challenge friends in this 42 School project"
homepage: https://localhost:8443
topics:
  - typescript
  - fastify
  - websocket
  - docker
  - nginx
  - oauth
  - jwt
  - gaming
  - multiplayer
  - real-time 