services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - database
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    command: npm run dev
    restart: always

  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "8443:443"
    restart: always
    

  database:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./backend/database:/data
    restart: on-failure
