services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - database
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "8080:8080"
    restart: always

  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "8443:443"
    depends_on:
      - backend
      - frontend
    restart: always

  database:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - sqlite_data:/data
    restart: on-failure

volumes:
  backend_node_modules:
  frontend_node_modules:
  sqlite_data: